name: Build and Release EXE

on:
  push:
    tags:
      - "v*.*.*"  # Trigger release on tag push (version format: vX.X.X)

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Specify Python version

      # Step 3: Install required Python packages
      - name: Install Python Dependencies
        run: |
          pip install pyinstaller selenium beautifulsoup4  # Install necessary dependencies

      # Step 4: Download ChromeDriver
      - name: Download ChromeDriver
        run: |
          Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip" -OutFile "chromedriver.zip"  # Download ChromeDriver
          Expand-Archive chromedriver.zip -DestinationPath .  # Extract the downloaded archive
          Move-Item -Path chromedriver.exe -Destination .\  # Move ChromeDriver to the correct location

      # Step 5: Build the EXE file using PyInstaller
      - name: Build EXE File
        run: |
          pyinstaller --onefile --windowed --add-binary "chromedriver.exe;." arabam_scraper_gui.py  # Create an EXE file with PyInstaller

      # Step 6: Prepare the release directory
      - name: Prepare Release Directory
        run: |
          mkdir release  # Create release directory
          move dist\arabam_scraper_gui.exe release\arabam_scraper_gui.exe  # Move the built EXE file to the release folder

      # Step 7: Upload the EXE file to GitHub Releases
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1  # GitHub action to upload files to releases
        with:
          files: release/arabam_scraper_gui.exe  # Specify the EXE file to upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically use the token to authenticate for GitHub API
